release 2020.08.11

diff --git a/src/i3flip b/src/i3flip
--- a/src/i3flip
+++ b/src/i3flip
@@ -3,8 +3,8 @@
 ___printversion(){
   
 cat << 'EOB' >&2
-i3flip - version: 0.052
-updated: 2019-02-22 by budRich
+i3flip - version: 0.099
+updated: 2020-08-09 by budRich
 EOB
 }
 
@@ -12,46 +12,75 @@ EOB
 
 main(){
 
-  __dir="${1,,}"
-  __dir=${__dir:0:1}
+  declare -g _msgstring
+  declare -i next prev
 
-  # "$__dir not valid direction"
-  [[ ! $__dir =~ u|r|l|d|n|p ]] \
-    && ERX "$1 is not a valid direction"
+  _dir=$1
+  ((__o[verbose])) && ERM "target direction: $_dir"
+  _dir=${_dir,,}
 
-  case "$__dir" in
-    r|d ) __dir=n ;;
-    l|u ) __dir=p ;;
+  eval "$(i3viswiz -p ${__o[json]:+--json "${__o[json]}"} | head -1)"
+  # unset unneeded variabels from viswiz
+  unset trgcon trgx trgy wall trgpar sx sy sw sh groupid
+
+  # by creating the wiz string, shellcheck will
+  # not complain about un-assigned variables 
+  wiz+="layout:${grouplayout:=} last:${lastingroup:=} "
+  wiz+="first:${firstingroup:=} "
+  wiz+="pos:${grouppos:=} size:${groupsize:=0} "
+
+  ((__o[verbose])) && ERM "w $wiz"
+
+  ((groupsize < 2)) && ERX only container in group
+
+  case "${_dir:0:1}" in
+
+    r|d|n ) 
+      next=1 prev=0
+      [[ "$grouplayout" =~ tabbed|splith ]] \
+        && ldir=right || ldir=down
+    ;;
+
+    l|u|p )
+      prev=1 next=0
+      [[ "$grouplayout" =~ tabbed|splith ]] \
+        && ldir=left || ldir=up
+    ;;
+
+    *     ) ERX "$1 is not a valid direction" ;;
   esac
 
-  declare -A __acur
-
-  eval "$(getcurrent)"
+  # focus/move normally
+  if (( (grouppos  > 1 && grouppos < groupsize)       
+   || ( (grouppos == 1 && next)
+   ||   (grouppos == groupsize && prev) ) )); then
+   
+   ((__o[move])) && cmd=move || cmd=focus
+   messy "$cmd  $ldir"
   
-  __orgtrg="$(gettarget)"
+  # warp focus/move to end of group
+  elif ((grouppos == 1)); then
+    if ((__o[move])); then
+      messy "[con_id=$lastingroup] mark --add --toggle fliptmp"
+      messy "move to mark fliptmp"
+      messy "[con_id=$lastingroup] mark --add --toggle fliptmp"
+    else
+      messy "[con_id=$lastingroup] focus"
+    fi
 
-  if ((${__o[move]:-0}!=1)); then
-    [[ ! ${__acur[layout]:-} =~ tabbed|stacked ]] && {
-
-      i3-msg -q focus parent
-      eval "$(getcurrent)"
-
-      [[ ! ${__acur[layout]:-} =~ tabbed|stacked ]] && {
-        i3-msg -q "[con_id=$__orgtrg]" focus
-        exit
-      }
-
-      __orgtrg="$(gettarget)"
-    }
-  fi
-
-  if ((__acur[total]==1)); then
-    ERX "only one window in container"
-  elif ((${__o[move]:-0}==1)); then
-    movetarget
+  # warp focus/move to start of group, (move+swap)
   else
-    i3-msg -q "[con_id=$__orgtrg]" focus, focus child
+    if ((__o[move])); then
+      messy "[con_id=$firstingroup] mark --add --toggle fliptmp"
+      messy "move to mark fliptmp, swap container with mark fliptmp"
+      messy "[con_id=$firstingroup] mark --add --toggle fliptmp"
+    else
+      messy "[con_id=$firstingroup] focus"
+    fi
   fi
+
+  ((__o[verbose])) || qflag='-q'
+  [[ -n $_msgstring ]] && i3-msg "${qflag:-}" "$_msgstring"
 }
 
 ___printhelp(){
@@ -62,8 +91,7 @@ i3flip - Tabswitching done right
 
 SYNOPSIS
 --------
-i3flip DIRECTION
-i3flip --move|-m DIRECTION
+i3flip [--move|-m] [--json JSON] [--verbose] [--dryrun] DIRECTION
 i3flip --help|-h
 i3flip --version|-v
 
@@ -71,7 +99,21 @@ OPTIONS
 -------
 
 --move|-m  
-Move the current tab instead of changing focus.
+Move the current container instead of changing
+focus.
+
+
+--json JSON  
+use JSON instead of output from  i3-msg -t
+get_tree
+
+
+--verbose  
+Print more information to stderr.
+
+
+--dryrun  
+Don't execute any i3 commands.
 
 --help|-h  
 Show help and exit.
@@ -84,151 +126,54 @@ EOB
 }
 
 
-ERM(){ >&2 echo "$*"; }
-ERR(){ >&2 echo "[WARNING]" "$*"; }
-ERX(){ >&2 echo "[ERROR]" "$*" && exit 1 ; }
+set -E
+trap '[ "$?" -ne 98 ] || exit 98' ERR
 
-getcurrent(){
-  i3-msg -t get_tree \
-  | awk -v RS=',' -F':' -v crit='"focused"' -v srch="true" '
-      BEGIN{fid="0";nid="0";nfo="0";nwi}
-
-      $1~"{\"id\"" || $2~"\"id\"" {
-        nwi=nwi+1;cid=$NF;aid[nwi]=cid}
-      $1 ~ crit && $2 ~ srch  {fid=cid}
-      $2 ~ crit && $3 ~ srch  {fid=cid}
-
-      $1=="\"layout\"" {alo[cid]=$2}
-
-      fid!="0" && $1=="\"focus\"" && $2~fid {focs=1}
-      focs=="1" && $NF~"[]]$"{end=1}
-      focs=="1" {gsub("[]]|[[]","",$NF);afo=$NF"|"afo;nfo++}
-      end=="1" {
-        j=nfo
-
-        for (i=nwi;i>0;i--){
-          if(fin==1){plo=alo[aid[i]];parid=aid[i];break}
-          if(aid[i]==fid){n=j}
-          if(afo ~ aid[i]){ord=aid[i]" "ord;--j}
-          
-          if(j==0){fin=1}
-        }
-        gsub("[\"]","",plo)
-
-        print "__acur[position]=" n
-        print "__acur[total]="    nfo
-        print "__acur[layout]="   plo
-        sub(/[[:space:]]*$/,"",ord)
-        print "__acur[order]=\""  ord "\""
-        print "__acur[parent]="   parid
-        print "__acur[focused]="  fid
-
-        exit
-      } 
-    '
+ERX() { >&2 echo  "[ERROR] $*" ; exit 98 ;}
+ERR() { >&2 echo  "[WARNING] $*"  ;}
+ERM() { >&2 echo  "$*"  ;}
+ERH(){
+  ___printhelp >&2
+  [[ -n "$*" ]] && printf '\n%s\n' "$*" >&2
+  exit 98
 }
 
-gettarget(){
-  local trg
-
-  [[ $__dir = n ]] \
-    && trg=$((__acur[position]==__acur[total]
-              ? 1
-              : __acur[position]+1
-            )) \
-    || trg=$((__acur[position]==1
-              ? __acur[total]
-              : __acur[position]-1
-            ))
-
-  aord=(${__acur[order]:-})
-  echo "${aord[$((trg-1))]}"
+messy() {
+  # arguments are valid i3-msg arguments
+  (( __o[verbose] )) && ERM "m $*"
+  (( __o[dryrun]  )) || _msgstring+="$*;"
 }
 
-movetarget(){
-  # print id of window left of the one we want to move to.
-  # if no warp is needed just print left|right
-  local trg ldir curid trgid bdir
 
-  [[ $__dir = n ]] \
-    && trg=$((__acur[position]==__acur[total]
-              ? 1
-              : 0
-            )) \
-    || trg=$((__acur[position]==1
-              ? __acur[total]
-              : 0
-            ))
-
-  aord=(${__acur[order]:-})
-  trgid="${aord[$((trg-1))]}"
-  curid="${__acur[focused]}"
-
-  if [[ ${__acur[layout]:-} =~ splith|stacked ]]; then
-    # case "$__dir" in
-    #   n) ldir=down ;;
-    #   p) ldir=up   ;;
-    # esac
-    # bdir=up
-    ERM "${__acur[layout]:-} moving with i3flip is currently only supported in tabbed or stacked containers"
-    return 1
-  else
-    case "$__dir" in
-      n) ldir=right ;;
-      p) ldir=left   ;;
-    esac
-    bdir=left
-  fi
-
-  if ((trg==0)); then
-    i3-msg -q "[con_id=$curid]" move "$ldir"
-  else
-
-    if ((trg==1)); then
-      i3-msg -q "[con_id=$trgid]" mark fliptmp
-      i3-msg -q "[con_id=$curid]" \
-        move to mark fliptmp, \
-        move "$bdir", \
-        focus
-      i3-msg -q "[con_id=$trgid]" unmark
-    else
-      i3-msg -q "[con_id=$trgid]" mark fliptmp
-      i3-msg -q "[con_id=$curid]" move to mark fliptmp, focus
-      i3-msg -q "[con_id=$trgid]" unmark
-    fi
-  fi
-}
 declare -A __o
-eval set -- "$(getopt --name "i3flip" \
-  --options "mhv" \
-  --longoptions "move,help,version," \
-  -- "$@"
+options="$(
+  getopt --name "[ERROR]:i3flip" \
+    --options "mhv" \
+    --longoptions "move,json:,verbose,dryrun,help,version," \
+    -- "$@" || exit 98
 )"
+
+eval set -- "$options"
+unset options
 
 while true; do
   case "$1" in
     --move       | -m ) __o[move]=1 ;; 
-    --help       | -h ) __o[help]=1 ;; 
-    --version    | -v ) __o[version]=1 ;; 
+    --json       ) __o[json]="${2:-}" ; shift ;;
+    --verbose    ) __o[verbose]=1 ;; 
+    --dryrun     ) __o[dryrun]=1 ;; 
+    --help       | -h ) ___printhelp && exit ;;
+    --version    | -v ) ___printversion && exit ;;
     -- ) shift ; break ;;
     *  ) break ;;
   esac
   shift
 done
 
-if [[ ${__o[help]:-} = 1 ]]; then
-  ___printhelp
-  exit
-elif [[ ${__o[version]:-} = 1 ]]; then
-  ___printversion
-  exit
-fi
-
 [[ ${__lastarg:="${!#:-}"} =~ ^--$|${0}$ ]] \
-  && __lastarg="" \
-  || true
+  && __lastarg="" 
 
 
-main "${@:-}"
+main "${@}"
 
 
diff --git a/src/i3get b/src/i3get
--- a/src/i3get
+++ b/src/i3get
@@ -3,68 +3,59 @@
 ___printversion(){
   
 cat << 'EOB' >&2
-i3get - version: 0.35
-updated: 2019-03-12 by budRich
+i3get - version: 0.631
+updated: 2020-08-10 by budRich
 EOB
 }
 
 
 
 main(){
-  local o result
 
-  declare -A __crit
+  declare -a _op         # output, populated in match()
+  declare -r _special= # used when searching for ws
+  declare -g _expression # makeexpression() via match()
+  declare -i timeout
 
-  for o in "${!__o[@]}"; do
-    [[ $o =~ synk|active|print ]] && continue
+  # _toprint what information to print, 
+  # defaults to n (container id)
+  declare -g _toprint=${__o[print]:-n}
 
-    if [[ $o = conid ]]; then
-      __crit[id]="${__o[$o]}"
-    elif [[ $o = winid ]]; then
-      __crit[window]="${__o[$o]}"
-    elif [[ $o = mark ]]; then
-      __crit[marks]="${__o[$o]}"
-    elif [[ $o = titleformat ]]; then
-      __crit[title_format]="${__o[$o]}"
-    else
-      __crit[$o]="${__o[$o]}"
-    fi
+  [[ -n ${_json:=${__o[json]}} ]] \
+    || _json=$(i3-msg -t get_tree)
 
-  done
+  match "$_json"
 
-  ((${__o[active]:-0}==1)) && __crit[focused]="true"
+  ((__o[synk])) && [[ -z "${_op[*]}" ]] && {
 
-  # if no search is given, search for active window
-  ((${#__crit[@]}==0)) && __crit[focused]="true"
+    timeout=$SECONDS
 
-  result="$(getwindow)"
+    match "$(i3-msg -t get_tree)"
 
-  ((${__o[synk]:-0}==1)) && {
-    # timeout after 10 seconds
-    for ((i=0;i<100;i++)); do 
-      sleep 0.1
-      result=$(getwindow)
-      [ -n "$result" ] && break
+    while [[ -z "${_op[*]}" ]]; do
+      ((SECONDS-timeout > 60)) && break
+      i3-msg -qt subscribe '["window"]'
+      match "$(i3-msg -t get_tree)"
     done
   }
 
-  if [ -n "$result" ]; then
-    printf '%s\n' "${result}"
-  else
-    ERX "no matching window."
-  fi
-  
+  [[ -n ${_op[*]} ]] && {
+    printf '%s\n' "${_op[@]}"
+    exit
+  }
+
+  ERX "no matching window."
 }
 
 ___printhelp(){
   
 cat << 'EOB' >&2
-i3get - Boilerplate and template maker for bash scripts
+i3get - prints info about a specific window to stdout
 
 
 SYNOPSIS
 --------
-i3get [--class|-c CLASS] [--instance|-i INSTANCE] [--title|-t TITLE] [--conid|-n CON_ID] [--winid|-d WIN_ID] [--mark|-m MARK] [--titleformat|-o TITLE_FORMAT] [--active|-a] [--synk|-y] [--print|-r OUTPUT]      
+i3get [--class|-c CLASS] [--instance|-i INSTANCE] [--title|-t TITLE] [--conid|-n CON_ID] [--id|-d WIN_ID] [--mark|-m MARK] [--titleformat|-o TITLE_FORMAT] [--active|-a] [--synk|-y] [--print|-r OUTPUT] [--json TREE]      
 i3get --help|-h
 i3get --version|-v
 
@@ -87,7 +78,7 @@ Search for windows with title.
 Search for windows with the given con_id
 
 
---winid|-d WIN_ID  
+--id|-d WIN_ID  
 Search for windows with the given window id
 
 
@@ -106,26 +97,52 @@ Currently active window (default)
 --synk|-y  
 Synch on. If this option is included,  script
 will wait till target window exist. (or timeout
-after 10 seconds).
+after 60 seconds).
 
 
 --print|-r OUTPUT  
 OUTPUT can be one or more of the following 
 characters:  
 
-|character | print
-|:---------|:-----
-|t       | title  
-|c       | class  
-|i       | instance  
-|d       | Window ID  
-|n       | Con_Id (default)  
-|m       | mark  
-|w       | workspace  
-|a       | is active  
-|f       | floating state  
-|o       | title format  
-|v       | visible state  
+
+|character | print            | return
+|:---------|:-----------------|:------
+|t         | title            | string
+|c         | class            | string
+|i         | instance         | string
+|d         | Window ID        | INT
+|n         | Con_Id (default) | INT
+|m         | mark             | JSON list
+|w         | workspace        | INT
+|a         | is active        | true or false
+|f         | floating state   | string
+|o         | title format     | string
+|e         | fullscreen       | 1 or 0
+|s         | sticky           | true or false
+|u         | urgent           | true or false
+
+Each character in OUTPUT will be tested and the
+return value will be printed on a new line. If no
+value is found, --i3get could not find: CHARACTER
+will get printed.
+
+In the example below, the target window did not
+have a mark:  
+
+
+   $ i3get -r tfcmw
+   /dev/pts/9
+   user_off
+   URxvt
+   --i3get could not find: m
+   1
+
+
+
+
+--json TREE  
+Use TREE instead of the output of  
+i3-msg -t get_tree
 
 
 --help|-h  
@@ -139,136 +156,232 @@ EOB
 }
 
 
-awklib() {
-target="${1:-main}"
-if [[ -n ${___dir:-} ]]; then #bashbud
-  if [[ $target = main ]]; then #bashbud
-    find "${___dir}/awklib" -maxdepth 1 -type f -exec cat "{}" \; #bashbud
-  fi #bashbud
-else #bashbud
+set -E
+trap '[ "$?" -ne 77 ] || exit 77' ERR
 
+ERX() { echo  "[ERROR] $*" >&2 ; exit 77 ;}
+ERR() { echo  "[WARNING] $*" >&2 ;}
+ERM() { echo  "$*" >&2 ;}
 
-  if [[ $target = main ]]; then
-cat << 'EOB'
-BEGIN {hit=0;start=0;trg=0}
+makeexpression() {
 
-# set crit array
-start == 0 {
-  if ($0 == "__START__") {
-    start = 1
-  } else if (/./) {
-    crit[$1]=$2
-    trg++
-  }
-}
+local mark o re crit format
 
-start == 1 && match($0,/([{]|"nodes":[[][{]|.*_rect":{|"window_properties":{)?"([a-z_]+)":[["]*(.+)$/,ma) {
+declare -A _c
 
-  key=ma[2]
-  
-  if (key == "title") {
-    var=gensub(/"$/,"",1,ma[3])
-  }
-  else {
-    var=gensub(/[]}"]/,"",1,ma[3])
-  }
+for o in "${!__o[@]}"; do
+  [[ $o =~ synk|active|print ]] && continue
 
+  crit=${__o[$o]}
 
-  # on every id, check if target is found, if so exit
-  # otherwise clear return array (except workspace key)
-  if (key == "id") {
-    if (hit == trg) exit
-    cid=var
-    hit=0
-    for(k in r){if(k!="w"){r[k]=""}}
-    if(sret ~ /[n]/)
-      r["n"]=cid
-  }
-
-  if (hit!=trg) {
-    for (c in crit) {
-      if (key == c && var ~ crit[c]) {
-        if (fid==cid) {hit++}
-        else {hit=1;fid=cid}
-      }
-    }
-  }
-
-  if (sret ~ /[t]/ && key == "title") {
-    r["t"]=gensub($1":","",1,$0)
-  }
-  
-  if (sret ~ /[c]/ && key == "class") {
-    r["c"]=var
-  }
-  
-  if (sret ~ /[i]/ && key == "instance") {
-    r["i"]=var
-  }
-  
-  if (sret ~ /[d]/ && key == "window") {
-    r["d"]=var
-  }
-  
-  if (sret ~ /[m]/ && key == "marks") {
-    r["m"]=var
-  }
-  
-  if (sret ~ /[a]/ && key == "focused") {
-    r["a"]=var
-  }
-  
-  if (sret ~ /[o]/ && key == "title_format") {
-    r["o"]=var
-  }
-  
-  if (sret ~ /[w]/ && key == "num") {
-    r["w"]=var
-  }
-  
-  if (sret ~ /[f]/ && key == "floating") {
-    r["f"]=var
-  }
-
-}
-
-END{
-  if (hit==0) exit
-  split(sret, aret, "")
-  for (i=1; i <= length(sret); i++) {
-    op=r[aret[i]]
-    gsub(/^["]|["]$/,"",op)
-    if(op!="")
-      printf("%s\n", op)
-  }
-}
-EOB
+  # allow ^ and $ re in criteria
+  if [[ $crit =~ [$]$ ]]; then
+    crit='[^"]*'"${crit%$}"
+  elif [[ $crit =~ ^[^] ]]; then
+    crit=${crit#^}'[^"]*'
+  elif [[ $crit =~ ^[^](.+)[$]$ ]]; then
+    crit=${BASH_REMATCH[1]}
   fi
-fi #bashbud
+
+  _c[$o]=$crit
+done
+
+# no criteria specified, search active window
+((__o[active] || !${#_c[@]})) && _c[active]=true
+: "${_c[active]:=true|false}"
+
+[[ -n ${_c[titleformat]} ]] \
+  && format="(\"title_format\":(\"${_c[titleformat]}\"),)" \
+  || format='("title_format":"([^"]+)",)?'
+
+[[ -n ${_c[mark]} ]] \
+  && mark="(\"marks\":(\[[^]]*\"${_c[mark]}\"[^]]*\]),)" \
+  || mark='("marks":(\[[^]]*\]),)?'
+
+# when workspace is important we insert the "_special"
+# character at all "num:" fields to be able to "backtrack"
+# the json. This replacement operation is somewhat expensive
+# and will slow down the overall execution of the script...
+if [[ ${__o[print]} =~ w || -n ${_c[workspace]} ]]; then
+  re="\"num$_special\":(${_c[workspace]:-[0-9-]+})"
+  re+=",[^$_special]+"
+else
+  re="(\{)"
+fi
+
+re+=$(cat << EOB
+"id":(${_c[conid]:-[0-9]+}),
+"type":"[^"]+",
+"orientation":"[^"]+",
+"scratchpad_state":"[^"]+",
+"percent":[0-9.]+,
+"urgent":(false|true),
+${mark}
+"focused":(${_c[active]}),
+"output":"[^"]+",
+"layout":"[^"]+",
+"workspace_layout":"[^"]+",
+"last_split_layout":"[^"]+",
+"border":"[^"]+",
+"current_border_width":[0-9-]+,
+"rect":[^}]+},
+"deco_rect":[^}]+},
+"window_rect":[^}]+},
+"geometry":[^}]+},
+"name":"?(${_c[title]:-[^\"]+})"?,
+${format}
+("window":(${_c[id]:-[0-9]+}),
+[^,]+,
+"window_properties":\{
+"class":"(${_c[class]:-[^\"]+})",
+"instance":"(${_c[instance]:-[^\"]+})",
+[^}]+\},
+"nodes":[^,]+,
+"floating_nodes":[^,]+,
+"focus":[^,]+,
+"fullscreen_mode":([0-9]),
+"sticky":(false|true),
+"floating":"([^"]+)",)
+EOB
+)
+
+# if criteria is mark || conid, window properties are optional
+[[ -n ${_c[mark]}${_c[conid]}${_c[titleformat]} ]] && re+='?'
+
+# remove all newline characters
+_expression="${re//$'\n'/}"
 }
 
-ERM(){ >&2 echo "$*"; }
-ERR(){ >&2 echo "[WARNING]" "$*"; }
-ERX(){ >&2 echo "[ERROR]" "$*" && exit 1 ; }
+# example node, this is formated with 'jq' the
+# output we parse have NO WHITESPACE other then
+# within strings.
+# 
+# "title_format" and "marks" entries are only present
+# if they contain a value.
+#
+# "name": can be null (not enclosed in quotes)
 
-getwindow(){
-  {
-    for c in "${!__crit[@]}"; do
-      echo -n "$c:${__crit[$c]},"
+# {
+#   "id": 94203263545520,
+#   "type": "con",
+#   "orientation": "none",
+#   "scratchpad_state": "none",
+#   "percent": 1,
+#   "urgent": false,
+#   "focused": false,
+#   "output": "__i3",
+#   "layout": "splith",
+#   "workspace_layout": "default",
+#   "last_split_layout": "splith",
+#   "border": "normal",
+#   "current_border_width": 2,
+#   "rect": {
+#     "x": 596,
+#     "y": 355,
+#     "width": 728,
+#     "height": 350
+#   },
+#   "deco_rect": {
+#     "x": 0,
+#     "y": 0,
+#     "width": 728,
+#     "height": 20
+#   },
+#   "window_rect": {
+#     "x": 2,
+#     "y": 0,
+#     "width": 724,
+#     "height": 348
+#   },
+#   "geometry": {
+#     "x": 0,
+#     "y": 0,
+#     "width": 724,
+#     "height": 348
+#   },
+#   "name": "/dev/pts/12",
+#   "title_format": "typiskt",
+#   "window": 8393677,
+#   "window_type": "unknown",
+#   "window_properties": {
+#     "class": "URxvt",
+#     "instance": "typiskt",
+#     "title": "/dev/pts/12",
+#     "transient_for": null
+#   },
+#   "nodes": [],
+#   "floating_nodes": [],
+#   "focus": [],
+#   "fullscreen_mode": 0,
+#   "sticky": false,
+#   "floating": "user_on",
+#   "swallows": []
+# }
+# ],
+# "floating_nodes": [],
+# "focus": [
+# 94203263545520
+# ],
+# "fullscreen_mode": 0,
+# "sticky": false,
+# "floating": "auto_off",
+# "swallows": []
+# }
+
+match() {
+
+  local json=$1 k
+
+  [[ -z $_expression ]] && makeexpression
+
+  declare -i i
+  declare -A ma
+
+  [[ $_toprint =~ w || -n ${__o[workspace]} ]] \
+    && json=${_json//\"num\":/\"num${_special}\":}
+
+  # name of the keys in array "ma" match the characters
+  # that can be used as arguments to --print (_toprint)
+  # optional capture groups are collected in the dummykey O
+  [[ $json =~ $_expression ]] && {
+    ma=(
+      [w]="${BASH_REMATCH[$((++i))]}" # "num:"             - INT
+      [n]="${BASH_REMATCH[$((++i))]}" # "id:"              - INT
+      [u]="${BASH_REMATCH[$((++i))]}" # "urgent:"          - false|true
+      [O]="${BASH_REMATCH[$((++i))]}" # ! optional group
+      [m]="${BASH_REMATCH[$((++i))]}" # "marks:"           - ["mark1","mark2"...]
+      [a]="${BASH_REMATCH[$((++i))]}" # "focused:"         - false|true
+      [t]="${BASH_REMATCH[$((++i))]}" # "name:"            - STRING
+      [O]="${BASH_REMATCH[$((++i))]}" # ! optional group
+      [o]="${BASH_REMATCH[$((++i))]}" # "title_format:"    - string
+      [O]="${BASH_REMATCH[$((++i))]}" # ! optional group
+      [d]="${BASH_REMATCH[$((++i))]}" # "window:"          - INT
+      [c]="${BASH_REMATCH[$((++i))]}" # "class:"           - STRING
+      [i]="${BASH_REMATCH[$((++i))]}" # "instance:"        - STRING
+      [e]="${BASH_REMATCH[$((++i))]}" # "fullscreen_mode:" - 0|1
+      [s]="${BASH_REMATCH[$((++i))]}" # "sticky:"          - true|false
+      [f]="${BASH_REMATCH[$((++i))]}" # "floating:"        - auto_off|auto_on|user_off|user_on
+    )
+
+    for ((i=0;i<${#_toprint};i++)); do
+      k=${_toprint:$i:1}
+      _op+=("${ma[$k]:---i3get could not find: $k}")
     done
 
-    echo -n "__START__,"
-
-    i3-msg -t get_tree
-  } | awk -v RS=',' -F':' -v sret="${__o[print]:-n}" -f <(awklib)
-    
+  }
 }
+
+
 declare -A __o
-eval set -- "$(getopt --name "i3get" \
-  --options "c:i:t:n:d:m:o:ayr:hv" \
-  --longoptions "class:,instance:,title:,conid:,winid:,mark:,titleformat:,active,synk,print:,help,version," \
-  -- "$@"
+options="$(
+  getopt --name "[ERROR]:i3get" \
+    --options "c:i:t:n:d:m:o:ayr:hv" \
+    --longoptions "class:,instance:,title:,conid:,id:,mark:,titleformat:,active,synk,print:,json:,help,version," \
+    -- "$@" || exit 77
 )"
+
+eval set -- "$options"
+unset options
 
 while true; do
   case "$1" in
@@ -276,32 +389,25 @@ while true; do
     --instance   | -i ) __o[instance]="${2:-}" ; shift ;;
     --title      | -t ) __o[title]="${2:-}" ; shift ;;
     --conid      | -n ) __o[conid]="${2:-}" ; shift ;;
-    --winid      | -d ) __o[winid]="${2:-}" ; shift ;;
+    --id         | -d ) __o[id]="${2:-}" ; shift ;;
     --mark       | -m ) __o[mark]="${2:-}" ; shift ;;
     --titleformat | -o ) __o[titleformat]="${2:-}" ; shift ;;
     --active     | -a ) __o[active]=1 ;; 
     --synk       | -y ) __o[synk]=1 ;; 
     --print      | -r ) __o[print]="${2:-}" ; shift ;;
-    --help       | -h ) __o[help]=1 ;; 
-    --version    | -v ) __o[version]=1 ;; 
+    --json       ) __o[json]="${2:-}" ; shift ;;
+    --help       | -h ) ___printhelp && exit ;;
+    --version    | -v ) ___printversion && exit ;;
     -- ) shift ; break ;;
     *  ) break ;;
   esac
   shift
 done
 
-if [[ ${__o[help]:-} = 1 ]]; then
-  ___printhelp
-  exit
-elif [[ ${__o[version]:-} = 1 ]]; then
-  ___printversion
-  exit
-fi
-
 [[ ${__lastarg:="${!#:-}"} =~ ^--$|${0}$ ]] \
   && __lastarg="" 
 
 
-main "${@:-}"
+main "${@}"
 
 
diff --git a/src/i3list b/src/i3list
--- a/src/i3list
+++ b/src/i3list
@@ -3,8 +3,8 @@
 ___printversion(){
   
 cat << 'EOB' >&2
-i3list - version: 0.045
-updated: 2019-02-19 by budRich
+i3list - version: 0.211
+updated: 2020-08-10 by budRich
 EOB
 }
 
@@ -14,20 +14,20 @@ main(){
 
   local crit srch
 
-  if [[ -z ${__o[*]:-} ]]; then
+  if [[ -z ${__o[*]} ]]; then
     crit=X srch=X
-  elif [[ -n ${__o[instance]:-} ]]; then
-    crit="instance" srch="${__o[instance]}"
-  elif [[ -n ${__o[class]:-} ]]; then
-    crit="class" srch="${__o[class]}"
-  elif [[ -n ${__o[conid]:-} ]]; then
-    crit="id" srch="${__o[conid]}"
-  elif [[ -n ${__o[winid]:-} ]]; then
-    crit="window" srch="${__o[winid]}"
-  elif [[ -n ${__o[mark]:-} ]]; then
-    crit="marks" srch="${__o[mark]}"
-  elif [[ -n ${__o[title]:-} ]]; then
-    crit="title" srch="${__o[title]}"
+  elif [[ -n ${srch:=${__o[instance]}} ]]; then
+    crit="instance"
+  elif [[ -n ${srch:=${__o[class]}} ]]; then
+    crit="class"
+  elif [[ -n ${srch:=${__o[conid]}} ]]; then
+    crit="id"
+  elif [[ -n ${srch:=${__o[winid]}} ]]; then
+    crit="window"
+  elif [[ -n ${srch:=${__o[mark]}} ]]; then
+    crit="marks"
+  elif [[ -n ${srch:=${__o[title]}} ]]; then
+    crit="title"
   else
     crit=X srch=X
   fi
@@ -45,17 +45,22 @@ i3list - list information about the current i3 session.
 
 SYNOPSIS
 --------
-i3list --instance|-i TARGET
-i3list --class|-c    TARGET
-i3list --conid|-n    TARGET
-i3list --winid|-d    TARGET
-i3list --mark|-m     TARGET
-i3list --title|-t    TARGET
+i3list [--json JSON]
+i3list --instance|-i TARGET [--json JSON]
+i3list --class|-c    TARGET [--json JSON]
+i3list --conid|-n    TARGET [--json JSON]
+i3list --winid|-d    TARGET [--json JSON]
+i3list --mark|-m     TARGET [--json JSON]
+i3list --title|-t    TARGET [--json JSON]
 i3list --help|-h
 i3list --version|-v
 
 OPTIONS
 -------
+
+--json JSON  
+use JSON instead of output from  i3-msg -t
+get_tree
 
 --instance|-i TARGET  
 Search for windows with a instance matching
@@ -82,6 +87,7 @@ Search for windows with a mark matching TARGET
 --title|-t TARGET  
 Search for windows with a title matching TARGET  
 
+
 --help|-h  
 Show help and exit.
 
@@ -98,7 +104,7 @@ cat << 'EOB'
 BEGIN {
   # sq contains a single quote for convenience
   sq = "'"
-  
+
   # act|trg == 0: active/target window not found yet
   # act|trg == 1: active/target window in process
   # act|trg == 2: active/target window processed
@@ -234,10 +240,26 @@ function descriptions() {
   desc["WFY"]="i3fyra Workspace Y position"
   desc["WFN"]="i3fyra Workspace name"
 
+  desc["XAB"]="family AB workspace"
+  desc["XAC"]="family AC workspace"
+  desc["XCD"]="family CD workspace"
+  desc["XBD"]="family BD workspace"
+
+  desc["VPA"]="virtual position A"
+  desc["VPB"]="virtual position B"
+  desc["VPC"]="virtual position C"
+  desc["VPD"]="virtual position D"
+
+
 }
 END {
 
   # mirror active to target if no criteria is given
+
+  if (WFI) {
+    setworkspace(WFI,"F")
+    layout["X" splits[3]]=workspace["WSF"]
+  }
 
   if (crit == "X") {
     for (k in window["A"]) {
@@ -292,11 +314,10 @@ END {
     }
 
     if (ENVIRON["I3FYRA_ORIENTATION"]=="vertical") {
-    splits[1]="AB"
-    splits[2]="CD"
-    splits[3]="AC"
-  }
-
+      splits[1]="AB"
+      splits[2]="CD"
+      splits[3]="AC"
+    }
 
     layout["LEX"]=layout["LVI"] layout["LHI"]
 
@@ -358,6 +379,11 @@ END {
         printf(stringformat, k, family[k], desc[k])
       }
     }
+  
+  }
+
+  for(k in memory){
+    printf(stringformat, k, memory[k], desc[k])
   }
 
   layout["LAL"]=splits[1] splits[2]
@@ -368,17 +394,19 @@ END {
     }
   }
 }
-hit!=0 && $0~"{" {hit++}
-hit!=0 && $0~"}" {hit--}
+hit && /[{]/ {hit++}
+hit && /[}]/ {hit--}
 
-$1 == "\"rect\"" && dimget != "workspace" {dimget="window"}
-$1 == "\"deco_rect\"" {dimget="tab"}
+$1 ~ /"rect"/ && dimget != "workspace" {dimget="window"}
+$1 ~ /"deco_rect"/ {dimget="tab"}
 
-match($0,/([{]|"nodes":[}][[]|.*_rect":{)?"([a-z_]+)":[["]*([^]}"]*)[]}"]*$/,ma) {
-  key=ma[2]
-  var=ma[3]
+$(NF-1) ~ /"(focus|id|window|name|num|width|height|x|y|floating|marks|layout|focused|instance|class|title)"$/ {
+  
+  key=gensub(/.*"([^"]+)"$/,"\\1","g",$(NF-1))
+  var=gensub(/[["]*([^]}"]+)[]}"]*$/,"\\1","g",$NF)
 
-  if (trg == 0 && key == crit && var ~ srch) {
+  
+  if (key == crit && !trg && var ~ srch) {
     if (key=="id") {curcid=var}
     window["T"]["TWC"]=curcid
     trg=1
@@ -386,16 +414,13 @@ match($0,/([{]|"nodes":[}][[]|.*_rect":{)?"([a-z_]+)":[["]*([^]}"]*)[]}"]*$/,ma)
 
   switch (key) {
     case "focus":
-      if (hit!=0) {
+      if (hit) {
         container["C"curcon"F"]=var
       } else {
         # define active workspace by id
         # (only useful when workspace is empty)
-        for (w in aws) {
-          if (var == w) {
-            setworkspace(w,"A")
-          }
-        }
+        for (w in aws) 
+          if (var == w) { setworkspace(w,"A") }
       }
     break
 
@@ -415,7 +440,7 @@ match($0,/([{]|"nodes":[}][[]|.*_rect":{)?"([a-z_]+)":[["]*([^]}"]*)[]}"]*$/,ma)
 
     case /^(width|height|x|y)$/ :
 
-      if (dimget != 0) {
+      if (dimget) {
         dim[curcid][dimget][key]=var
       }
 
@@ -425,7 +450,7 @@ match($0,/([{]|"nodes":[}][[]|.*_rect":{)?"([a-z_]+)":[["]*([^]}"]*)[]}"]*$/,ma)
 
     case "id":
       curcid=var
-      if (hit!=0) {conta[curcon]["id"]=curcid}
+      if (hit) {conta[curcon]["id"]=curcid}
     break
 
     case "floating":
@@ -450,22 +475,23 @@ match($0,/([{]|"nodes":[}][[]|.*_rect":{)?"([a-z_]+)":[["]*([^]}"]*)[]}"]*$/,ma)
         acon[curcon]=curcid
       }
 
-      else if (var ~ /^i34X.*/ && fourspace != 1) {
-        # if mainsplit container exist, get i3fyra
-        # workspace on next occurrence of "num".
 
-        setworkspace(curwsid,"F")
-        fourspace=1
+      else if (match(var,/^i34X(.+)/,splitmark)) {
+        # if mainsplit (splits[3]) container exist
+        # curcid is id of fyra workspace (WFI)
+        if (splitmark[1] == splits[3]) {
+          WFI=curcid
+        } 
+        
+        layout["X" splitmark[1]]=curws  
       }
 
-      else if (var ~ /i34M(AB|CD|AC|BD)/) {
-        split(var,mrksplt,"=")
-        outsplit[substr(var,4,3)]=mrksplt[2]
+      else if (match(var,/^i34([FM].{2})=(.*)/,splitmark)) {
+        memory[splitmark[1]]=splitmark[2]
       }
 
-      else if (var ~ /i34F(AB|CD|AC|BD)/) {
-        split(var,mrksplt,"=")
-        family[substr(var,4,3)]=mrksplt[2]
+      else if (match(var,/^i34(VP[ABCD])=(.*)/,splitmark)) {
+        memory[splitmark[1]]=splitmark[2]
       }
 
     break
@@ -535,59 +561,56 @@ function setworkspace(cid,type) {
 EOB
 }
 
-ERM(){ >&2 echo "$*"; }
-ERR(){ >&2 echo "[WARNING]" "$*"; }
-ERX(){ >&2 echo "[ERROR]" "$*" && exit 1 ; }
+set -E
+trap '[ "$?" -ne 98 ] || exit 98' ERR
+
+ERX() { echo  "[ERROR] $*" >&2 ; exit 98 ;}
+ERR() { echo  "[WARNING] $*" >&2 ;}
+ERM() { echo  "$*" >&2 ;}
 
 printlist(){
 
-  local crit="${1:-X}"
-  local srch="${2:-X}"
-  local toprint="${3:-all}"
+  [[ -n ${_json:=${__o[json]}} ]] \
+    || _json=$(i3-msg -t get_tree)
 
-  i3-msg -t get_tree | awk -f <(awklib) \
-                           -F':' \
-                           -v RS=',' \
-                           -v crit="${crit}" \
-                           -v srch="${srch}" \
-                           -v toprint="${toprint}" 
+  awk -f <(awklib)                                  \
+         FS=: RS=, crit="$1" srch="$2" toprint="$3" \
+         <<< "$_json"
 }
+
+
 declare -A __o
-eval set -- "$(getopt --name "i3list" \
-  --options "i:c:n:d:m:t:hv" \
-  --longoptions "instance:,class:,conid:,winid:,mark:,title:,help,version," \
-  -- "$@"
+options="$(
+  getopt --name "[ERROR]:i3list" \
+    --options "i:c:n:d:m:t:hv" \
+    --longoptions "json:,instance:,class:,conid:,winid:,mark:,title:,help,version," \
+    -- "$@" || exit 98
 )"
+
+eval set -- "$options"
+unset options
 
 while true; do
   case "$1" in
+    --json       ) __o[json]="${2:-}" ; shift ;;
     --instance   | -i ) __o[instance]="${2:-}" ; shift ;;
     --class      | -c ) __o[class]="${2:-}" ; shift ;;
     --conid      | -n ) __o[conid]="${2:-}" ; shift ;;
     --winid      | -d ) __o[winid]="${2:-}" ; shift ;;
     --mark       | -m ) __o[mark]="${2:-}" ; shift ;;
     --title      | -t ) __o[title]="${2:-}" ; shift ;;
-    --help       | -h ) __o[help]=1 ;; 
-    --version    | -v ) __o[version]=1 ;; 
+    --help       | -h ) ___printhelp && exit ;;
+    --version    | -v ) ___printversion && exit ;;
     -- ) shift ; break ;;
     *  ) break ;;
   esac
   shift
 done
 
-if [[ ${__o[help]:-} = 1 ]]; then
-  ___printhelp
-  exit
-elif [[ ${__o[version]:-} = 1 ]]; then
-  ___printversion
-  exit
-fi
-
 [[ ${__lastarg:="${!#:-}"} =~ ^--$|${0}$ ]] \
-  && __lastarg="" \
-  || true
+  && __lastarg="" 
 
 
-main "${@:-}"
+main "${@}"
 
 
